version: "3.9"

services:
  node-api:
    build: ./node-service
    ports:
      - "3000:3000"
    container_name: node-sensor-service

  python-api:
    build: ./python-service
    ports:
      - "8000:8000"
    container_name: python-sensor-service
